#!/bin/zsh

# ==> Colors
#alias ls="exa --group-directories-first --color=auto --icons"
[ "$(uname -s)" = "Darwin" ] && alias ls="ls -G" || alias ls="ls --color=auto"
alias grep="grep --color=auto"
lsclr() {for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done}
[ "$(uname -s)" = "Darwin" ] && alias diff="colordiff" || alias diff="diff --color=auto"

# ==> Python
alias senv="source env/bin/activate"
alias svenv="source venv/bin/activate"

# ==> Dragon drag and drop
alias dragon="dragon-drag-and-drop -a -x"

# ==> Miscellaneous
alias rscp="rsync -avPc" # add -z to compress
alias scpng="scanimage --progress --format=png --output-file"
alias mk="make -j$(($(nproc)+1))"
alias eat_newline="perl -pi -e 'chomp if eof'"

winepref() {
    WINEPREFIX="$HOME/.local/share/wineprefixes/$1"
    shift
    $@
}

# ==> Arch-specific
if command -v pacman &> /dev/null; then
    alias rmorphans="sudo pacman -Rns \$(pacman -Qdtq | xargs)"
    if command -v fzf &> /dev/null; then
        if command -v paru &> /dev/null; then
            alias addpkg="paru -Slq | fzf --multi --preview 'paru -Si {1}' | xargs -ro sudo paru -S"
            alias rmpkg="paru -Qq | fzf --multi --preview 'paru -Qi {1}' | xargs -ro sudo paru -Rns"
        else
            alias addpkg="pacman -Slq | fzf --multi --preview 'pacman -Si {1}' | xargs -ro sudo pacman -S"
            alias rmpkg="pacman -Qq | fzf --multi --preview 'pacman -Qi {1}' | xargs -ro sudo pacman -Rns"
        fi
    fi
fi
