#!/bin/sh -e

mode="$1"

choice="$(niri msg -j workspaces | jq -cr '.[] | "\(.idx) \(.name // "")"' | sort -n | fuzzel --dmenu)"
IFS=" " read -r id name <<EOF
$choice
EOF
echo "Chose workspace: $id, $name"

case "$mode" in
	focus)
		niri msg action focus-workspace "$id"
		;;
	move)
		niri msg action move-column-to-workspace "$id"
		;;
	"*")
		notify-send -a "niri/scripts/choose-workspace" "Invalid mode"
		;;
esac
