include=~/.local/share/bobascheme/themes/fuzzel/bobascheme_dark.ini

terminal=xdg-terminal-exec
filter-desktop=yes
show-actions=yes
launch-prefix=uwsm app --

[key-bindings]
prev=Up Control+p Control+k
next=Down Control+n Control+j

# this keybind conflicts with Ctrl-k; see Bash keyboard shortcuts
# https://gist.github.com/tuxfight3r/60051ac67c5f0445efee
delete-line-forward=none
