[hyprsplit]
enabled = true
failed = false
filename = 'hyprsplit.so'

[repository]
hash = '3a2507f17c789a63ca6143686e5001f79dcdd944'
name = 'hyprsplit'
rev = ''
url = 'https://github.com/shezdy/hyprsplit'