[hyprsplit]
enabled = true
failed = false
filename = 'hyprsplit.so'

[repository]
hash = '22c2e79bba61b56971d7b5363d047f2a5c7b8c71'
name = 'hyprsplit'
rev = ''
url = 'https://github.com/shezdy/hyprsplit'