[hyprsplit]
enabled = true
failed = false
filename = 'hyprsplit.so'

[repository]
hash = '73452b8a1deb5c260373f68ba1daba3a426da380'
name = 'hyprsplit'
rev = ''
url = 'https://github.com/shezdy/hyprsplit'