[hyprsplit]
enabled = true
failed = false
filename = 'hyprsplit.so'

[repository]
hash = '27eef65a6b1aafc0baa34aba3b89306aa0c59d9e'
name = 'hyprsplit'
rev = ''
url = 'https://github.com/shezdy/hyprsplit'