#!/bin/zsh

# ---> Colors
alias ls="exa --group-directories-first --color=auto --icons"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias ccat="highlight --out-format=xterm256"
lsclr() {for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done}

# ---> Miscellaneous
alias mntdrv="sudo mount -o uid=$(whoami)"
alias dragon="dragon-drag-and-drop -a -x"
alias rscp="rsync -atzvP"
alias scpng="scanimage --progress --format=png --output-file"

# ---> Arch-specific
if command -v pacman &> /dev/null; then
    alias rmorphans="sudo pacman -Rns $(pacman -Qdtq | xargs)"
    if command -v fzf &> /dev/null; then
        alias addpkg="pacman -Slq | fzf --multi --preview 'pacman -Si {1}' | xargs -ro sudo pacman -S"
        alias rmpkg="pacman -Qq | fzf --multi --preview 'pacman -Qi {1}' | xargs -ro sudo pacman -Rns"
    fi
fi
