#!/usr/bin/env python3
# Install some settings I want synchronized between my various systems

# TODO: would be nice to run `gsettings monitor` on all schemas to watch which
#       values actually do end up getting updated; I tested and that does work

from pathlib import Path
import subprocess
import sys
import tomllib

# action: set or reset
# prefs dict: dict[ schema -> dict[key,value] ]
def perform_prefs(action: str, prefs: dict[str, dict[str, any]]) -> bool:
	had_error = False
	for schema, pref in prefs.items():
		for key, value in pref.items():
			if isinstance(value, bool):
				value = str(value).lower()
			else:
				value = str(value)
			# TODO: should I have used some GIO library or something instead of calling the `gsettings` command?
			# capture_output=False by default, so it flows up to the main terminal output
			output = subprocess.run(["gsettings", action, schema, key, value])
			try:
				output.check_returncode()
				print(f"[*] Set {schema} {key} = '{value}'")
			except subprocess.CalledProcessError:
				had_error = True
				print(f"[*] Failed to set {schema} {key} to '{value}'")

	return had_error


with open(Path.home()/".config"/"bbaovanc"/"gsettings"/"gsettings.toml", "rb") as f:
	data = tomllib.load(f)

# flatten the multi-layered structure of preferences into a list of schema -> key -> value
any_errors = False
if perform_prefs("set", data["set"]):
	any_errors = True

if any_errors:
	print("\n[*] There were error(s) changing some settings")
	exit(1)
