# vim: foldmethod=marker

[include]
files = ["~/documents/shared-docs/dotfiles/noctalia/"]

# disable plugins for now
[[plugins.source]]
enabled = false
kind = "git"
location = "https://github.com/noctalia-dev/official-plugins"
name = "official"
[[plugins.source]]
enabled = false
kind = "git"
location = "https://github.com/noctalia-dev/community-plugins"
name = "community"


[theme]
mode = "dark"
source = "custom"
custom_palette = "bobascheme"

[wallpaper]
enabled = true
fill_mode = "crop"
directory = "~/wallpapers"
#edge_smoothness =
[wallpaper.default]
path = "/home/bbaovanc/wallpapers/hifdzul-muhammad-siregar-F4cib3eJqT0-unsplash.jpg"


[shell]
clipboard_enabled = false
time_format = "{:%-I:%M %p}"
date_format = "%A, %Y-%m-%d"
[shell.session.power]
suspend = "~/.config/noctalia/scripts/sleep.sh"

[osd.kinds]
caffeine = false
media = false
lock_keys = false


# Services {{{

[battery]
warning_threshold = 15

[idle]
behavior_order = ["screen_off", "lock", "suspend"]
pre_action_fade_seconds = 5.0
[idle.behavior.screen-off]
timeout = 300
action = "screen_off"
[idle.behavior.lock]
timeout = 305
action = "lock"
[idle.behavior.suspend]
timeout = 310
action = "suspend"
lock_before_suspend = true

# [location]
# [nightlight]

# [notification]
# enable_daemon = true
# show_app_name = true
# show_actions = true

[system.monitor]
enabled = false

# }}}


# Bar {{{

[bar.default]
widget_spacing = 10
start = [
	"session",
	#"launcher",
	"workspaces",
]
center = [
	"media",
]
end = [
	"caffeine",
	"clipboard", # disabled under [shell]
	"brightness",
	"volume",
	#"battery",
	"group:battery",
	#"battery_time",
	"battery/trackpad",
	"bluetooth",
	"network",
	"clock",
	"control-center",
	"notifications",
	"tray",
]
position = "top"
enabled = true
auto_hide = false

background_opacity = 0.65
radius = 0
concave_edge_corners = false
margin_ends = 0
font_family = "sans"
shadow = true
contact_shadow = false

# }}}

# Lockscreen {{{
[lockscreen_widgets]
enabled = true

[lockscreen_widgets.widget.clock]
box_height = 0.0
box_width = 0.0
cx = 188.0
cy = 89.0
rotation = 0.0
type = "clock"
[lockscreen_widgets.widget.clock.settings]
background_color = "surface"
background_opacity = 0.0
center_text = false
clock_style = "digital"
format = "{:%-I:%M %p}"
# }}}

# Widget configuration {{{
[[bar.default.capsule_group]]
id = "battery"
members = ["battery", "battery_rate"]
padding = 5
opacity = 0
widget_spacing = 5
[widget.battery]
display_mode = "glyph"
label_content = "percent"
warning_color = "error"
[widget.battery_rate]
type = "battery"
display_mode = "none"
label_content = "rate"
warning_color = "error"
[widget.battery_time]
type = "battery"
label_content = "time"

[widget.clock]
format = "{:%a %b %e %-I:%M %p}"

[widget.control-center]
# https://tabler.io/icons
glyph = "adjustments"

[widget.media]
max_length = 400
title_scroll = "on_hover"
hide_when_no_media = true

[widget.network]
show_label = false
vpn_status = "both"

[widget.workspaces]
style = "regular"
show_labels = true
label_source = "name"
max_label_chars = 99
occupied_color = "#00000000"
empty_color = "#00000000"

#[widget.tray]

# Actions
[widget.brightness.actions]
scroll_up = "brightness-up current 1%"
scroll_down = "brightness-down current 1%"
[widget.volume.actions]
scroll_up = "volume-up 1%"
scroll_down = "volume-down 1%"

# }}}
